[package]
name = "headless-cms"
version = "0.1.0"
edition = "2021"
authors = ["ofuji.works@gmail.com"]

[[bin]]
name = "app"
path = "src/bin/app.rs"

[workspace]
members = [
  "application",
  "domain",
  "infrastructure",
  "interface",
]

[workspace.dependencies]
anyhow = "1.0.93"
async-trait = "0.1.83"
rstest = "0.23.0"
tokio = { version = "1.41.1", features = ["full"] }
derive-new = "0.7.0"
infrastructure = { path = "./infrastructure" }

[dependencies]
tokio.workspace = true
infrastructure.workspace = true
 
