services:
  app:
    container_name: headless-cms_app
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      args:
        PORT: ${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}

  redis:
    container_name: headless-cms_redis
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  postgres:
    image: postgres:15
    container_name: headless-cms_db 
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgres/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USERNAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    container_name: headless-cms_storage
    command: ["server", "/data", "--console-address", ":${STORAGE_CONSOLE_PORT}"]
    volumes:
      - storage:/data
    environment:
      - MINIO_ROOT_USER=${STORAGE_USER}
      - MINIO_ROOT_PASSWORD=${STORAGE_PASSWORD}
    ports:
      - ${STORAGE_PORT}:${STORAGE_PORT}
      - ${STORAGE_CONSOLE_PORT}:${STORAGE_CONSOLE_PORT}

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: headless-cms_keycloak
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command:
      - start-dev
    volumes:
      - keycloak:/opt/keycloak/data

volumes:
  db:
    driver: local
  storage:
    driver: local
  keycloak:
    driver: local

