[env]
APP_PORT = 8080
REDIS_PORT = 6379
POSTGRES_PORT = 5432
DATABASE_HOST = "localhost"
DATABASE_USERNAME = "app"
DATABASE_PASSWORD = "passw0rd"
DATABASE_NAME = "app"
DATABASE_URL = "postgresql://${DATABASE_HOST}:${POSTGRES_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}"

[config]
default_to_workspace = false

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "${@}"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "--all", "--all-targets", "${@}"]

[tasks.watch]
dependencies = ["compose-up-db-for-linux"]
run_task = [{ name = ["fmt", "clippy"] }]
watch = true

[tasks.run]
command = "cargo"
args = ["run", "${@}"]

[tasks.docker-run]
command = "docker"
args = ["compose", "up", "--build", "-d"]

[tasks.docker-run-for-linux]
command = "sudo"
args = ["docker", "compose", "up", "--build", "${@}"]

[tasks.compose-up-db]
command = "docker"
args = ["compose", "up", "-d", "postgres"]

[tasks.compose-up-db-for-linux]
command = "sudo"
args = ["docker", "compose", "up", "-d", "postgres"]

[tasks.docker-down]
command = "docker"
args = ["compose", "down", "${@}"]

[tasks.docker-down-for-linux]
command = "sudo"
args = ["docker-compose", "down"]

[tasks.docker-remove]
command = "docker"
args = ["compose", "down", "-v"]

[tasks.docker-remove-for-linux]
command = "sudo"
args = ["docker-compose", "down", "-v"]

[tasks.migrate]
dependencies = ["compose-up-db-for-linux"]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help" }
script = '''
#!/bin/bash
until sqlx migrate run --source infrastructure/migrations; do
  sleep 1
done
'''

[tasks.migrate-revert]
dependencies = ["compose-up-db-for-linux"]
command = "sqlx"
args = ["migrate", "revert", "--source", "infrastructure/migrations"]

[tasks.sqlx]
install_crate = { crate_name = "sqlx-cli", binary = "sqlx", test_arg = "--help" }
command = "sqlx"
args = ["${@}", "--source", "infrastructure/migrations"]

[tasks.psql]
command = "sudo"
args = [
  "docker", "run", "-it", "--rm",
  "--network", "host",
  "-v", "${PWD}:/work",
  "postgres:15", "psql", "${DATABASE_URL}",
  "-f", "/work/data/initial_setup.sql"
]

