[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
anyhow.workspace = true
rstest.workspace = true
tokio.workspace = true
sqlx = { version = "0.8.2", features = ["runtime-tokio", "uuid", "chrono", "macros", "postgres", "migrate"] }
